/** Chapter (kitab) titles for every hadith collection Falah publishes.
 *
 * GENERATED — do not edit by hand. Run `node scripts/build-hadith-chapters.mjs`
 * to rebuild, which re-verifies the numbering against both upstream datasets.
 *
 * Committed rather than fetched for the same reason lib/quran-meta.ts is:
 * chapter slugs are the URLs (/hadith/sahih-bukhari/book-of-belief), and they
 * must not be able to shift because a CDN changed. Tuples keep it small.
 */

export type ChapterTitle = readonly [
  n: number,
  arabic: string,
  english: string,
  /** The URL segment: /hadith/sahih-bukhari/book-of-belief. Shared by both
   * locales, because switching language only swaps the /en /ar prefix. */
  slug: string,
];

export const CHAPTER_TITLES: Record<string, readonly ChapterTitle[]> = {
  bukhari: [
    [1, "كتاب بدء الوحى", "Revelation", "revelation"],
    [2, "كتاب الإيمان", "Belief", "belief"],
    [3, "كتاب العلم", "Knowledge", "knowledge"],
    [4, "كتاب الوضوء", "Ablutions (Wudu')", "ablutions-wudu"],
    [5, "كتاب الغسل", "Bathing (Ghusl)", "bathing-ghusl"],
    [6, "كتاب الحيض", "Menstrual Periods", "menstrual-periods"],
    [7, "كتاب التيمم", "Rubbing hands and feet with dust (Tayammum)", "rubbing-hands-and-feet-with-dust-tayammum"],
    [8, "كتاب الصلاة", "Prayers (Salat)", "prayers-salat"],
    [9, "كتاب مواقيت الصلاة", "Times of the Prayers", "times-of-the-prayers"],
    [10, "كتاب الأذان", "Call to Prayers (Adhaan)", "call-to-prayers-adhaan"],
    [11, "كتاب الجمعة", "Friday Prayer", "friday-prayer"],
    [12, "كتاب صلاة الخوف", "Fear Prayer", "fear-prayer"],
    [13, "كتاب العيدين", "The Two Festivals (Eids)", "two-festivals-eids"],
    [14, "كتاب الوتر", "Witr Prayer", "witr-prayer"],
    [15, "كتاب الاستسقاء", "Invoking Allah for Rain (Istisqaa)", "invoking-allah-for-rain-istisqaa"],
    [16, "كتاب الكسوف", "Eclipses", "eclipses"],
    [17, "كتاب سجود القرآن", "Prostration During Recital of Qur'an", "prostration-during-recital-of-quran"],
    [18, "كتاب التقصير", "Shortening the Prayers (At-Taqseer)", "shortening-the-prayers-at-taqseer"],
    [19, "كتاب التهجد", "Prayer at Night (Tahajjud)", "prayer-at-night-tahajjud"],
    [20, "كتاب فضل الصلاة فى مسجد مكة والمدينة", "Virtues of Prayer at Masjid Makkah and Madinah", "virtues-of-prayer-at-masjid-makkah-and-madinah"],
    [21, "كتاب العمل فى الصلاة", "Actions while Praying", "actions-while-praying"],
    [22, "كتاب السهو", "Forgetfulness in Prayer", "forgetfulness-in-prayer"],
    [23, "كتاب الجنائز", "Funerals (Al-Janaa'iz)", "funerals-al-janaaiz"],
    [24, "كتاب الزكاة", "Obligatory Charity Tax (Zakat)", "obligatory-charity-tax-zakat"],
    [25, "كتاب الحج", "Hajj (Pilgrimage)", "hajj-pilgrimage"],
    [26, "كتاب العمرة", "`Umrah (Minor pilgrimage)", "umrah-minor-pilgrimage"],
    [27, "كتاب المحصر", "Pilgrims Prevented from Completing the Pilgrimage", "pilgrims-prevented-from-completing-the-pilgrimage"],
    [28, "كتاب جزاء الصيد", "Penalty of Hunting while on Pilgrimage", "penalty-of-hunting-while-on-pilgrimage"],
    [29, "كتاب فضائل المدينة", "Virtues of Madinah", "virtues-of-madinah"],
    [30, "كتاب الصوم", "Fasting", "fasting"],
    [31, "كتاب صلاة التراويح", "Praying at Night in Ramadaan (Taraweeh)", "praying-at-night-in-ramadaan-taraweeh"],
    [32, "كتاب فضل ليلة القدر", "Virtues of the Night of Qadr", "virtues-of-the-night-of-qadr"],
    [33, "كتاب الاعتكاف", "Retiring to a Mosque for Remembrance of Allah (I'tikaf)", "retiring-to-a-mosque-for-remembrance-of-allah-itikaf"],
    [34, "كتاب البيوع", "Sales and Trade", "sales-and-trade"],
    [35, "كتاب السلم", "Sales in which a Price is paid for Goods to be Delivered Later (As-Salam)", "sales-in-which-a-price-is-paid-for-goods-to-be-delivered"],
    [36, "كتاب الشفعة", "Shuf'a", "shufa"],
    [37, "كتاب الإجارة", "Hiring", "hiring"],
    [38, "كتاب الحوالات", "Transferance of a Debt from One Person to Another (Al-Hawaala)", "transferance-of-a-debt-from-one-person-to-another-al-hawaala"],
    [39, "كتاب الكفالة", "Kafalah", "kafalah"],
    [40, "كتاب الوكالة", "Representation, Authorization, Business by Proxy", "representation-authorization-business-by-proxy"],
    [41, "كتاب المزارعة", "Agriculture", "agriculture"],
    [42, "كتاب المساقاة", "Distribution of Water", "distribution-of-water"],
    [43, "كتاب فى الاستقراض", "Loans, Payment of Loans, Freezing of Property, Bankruptcy", "loans-payment-of-loans-freezing-of-property-bankruptcy"],
    [44, "كتاب الخصومات", "Khusoomaat", "khusoomaat"],
    [45, "كتاب فى اللقطة", "Lost Things Picked up by Someone (Luqatah)", "lost-things-picked-up-by-someone-luqatah"],
    [46, "كتاب المظالم", "Oppressions", "oppressions"],
    [47, "كتاب الشركة", "Partnership", "partnership"],
    [48, "كتاب الرهن", "Mortgaging", "mortgaging"],
    [49, "كتاب العتق", "Manumission of Slaves", "manumission-of-slaves"],
    [50, "كتاب المكاتب", "Makaatib", "makaatib"],
    [51, "كتاب الهبة وفضلها والتحريض عليها", "Gifts", "gifts"],
    [52, "كتاب الشهادات", "Witnesses", "witnesses"],
    [53, "كتاب الصلح", "Peacemaking", "peacemaking"],
    [54, "كتاب الشروط", "Conditions", "conditions"],
    [55, "كتاب الوصايا", "Wills and Testaments (Wasaayaa)", "wills-and-testaments-wasaayaa"],
    [56, "كتاب الجهاد والسير", "Fighting for the Cause of Allah (Jihaad)", "fighting-for-the-cause-of-allah-jihaad"],
    [57, "كتاب فرض الخمس", "One-fifth of Booty to the Cause of Allah (Khumus)", "one-fifth-of-booty-to-the-cause-of-allah-khumus"],
    [58, "كتاب الجزية والموادعة", "Jizyah and Mawaada'ah", "jizyah-and-mawaadaah"],
    [59, "كتاب بدء الخلق", "Beginning of Creation", "beginning-of-creation"],
    [60, "كتاب أحاديث الأنبياء", "Prophets", "prophets"],
    [61, "كتاب المناقب", "Virtues and Merits of the Prophet (pbuh) and his Companions", "virtues-and-merits-of-the-prophet-pbuh-and-his-companions"],
    [62, "كتاب فضائل أصحاب النبى صلى الله عليه وسلم", "Companions of the Prophet", "companions-of-the-prophet"],
    [63, "كتاب مناقب الأنصار", "Merits of the Helpers in Madinah (Ansaar)", "merits-of-the-helpers-in-madinah-ansaar"],
    [64, "كتاب المغازى", "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)", "military-expeditions-led-by-the-prophet-pbuh-al-maghaazi"],
    [65, "كتاب التفسير", "Prophetic Commentary on the Qur'an (Tafseer of the Prophet (pbuh))", "prophetic-commentary-on-the-quran-tafseer-of-the-prophet"],
    [66, "كتاب فضائل القرآن", "Virtues of the Qur'an", "virtues-of-the-quran"],
    [67, "كتاب النكاح", "Wedlock, Marriage (Nikaah)", "wedlock-marriage-nikaah"],
    [68, "كتاب الطلاق", "Divorce", "divorce"],
    [69, "كتاب النفقات", "Supporting the Family", "supporting-the-family"],
    [70, "كتاب الأطعمة", "Food, Meals", "food-meals"],
    [71, "كتاب العقيقة", "Sacrifice on Occasion of Birth (`Aqiqa)", "sacrifice-on-occasion-of-birth-aqiqa"],
    [72, "كتاب الذبائح والصيد", "Hunting, Slaughtering", "hunting-slaughtering"],
    [73, "كتاب الأضاحي", "Al-Adha Festival Sacrifice (Adaahi)", "al-adha-festival-sacrifice-adaahi"],
    [74, "كتاب الأشربة", "Drinks", "drinks"],
    [75, "كتاب المرضى", "Patients", "patients"],
    [76, "كتاب الطب", "Medicine", "medicine"],
    [77, "كتاب اللباس", "Dress", "dress"],
    [78, "كتاب الأدب", "Good Manners and Form (Al-Adab)", "good-manners-and-form-al-adab"],
    [79, "كتاب الاستئذان", "Asking Permission", "asking-permission"],
    [80, "كتاب الدعوات", "Invocations", "invocations"],
    [81, "كتاب الرقاق", "To make the Heart Tender (Ar-Riqaq)", "to-make-the-heart-tender-ar-riqaq"],
    [82, "كتاب القدر", "Divine Will (Al-Qadar)", "divine-will-al-qadar"],
    [83, "كتاب الأيمان والنذور", "Oaths and Vows", "oaths-and-vows"],
    [84, "كتاب كفارات الأيمان", "Expiation for Unfulfilled Oaths", "expiation-for-unfulfilled-oaths"],
    [85, "كتاب الفرائض", "Laws of Inheritance (Al-Faraa'id)", "laws-of-inheritance-al-faraaid"],
    [86, "كتاب الحدود", "Limits and Punishments set by Allah (Hudood)", "limits-and-punishments-set-by-allah-hudood"],
    [87, "كتاب الديات", "Blood Money (Ad-Diyat)", "blood-money-ad-diyat"],
    [88, "كتاب استتابة المرتدين والمعاندين وقتالهم", "Apostates", "apostates"],
    [89, "كتاب الإكراه", "(Statements made under) Coercion", "statements-made-under-coercion"],
    [90, "كتاب الحيل", "Tricks", "tricks"],
    [91, "كتاب التعبير", "Interpretation of Dreams", "interpretation-of-dreams"],
    [92, "كتاب الفتن", "Afflictions and the End of the World", "afflictions-and-the-end-of-the-world"],
    [93, "كتاب الأحكام", "Judgments (Ahkaam)", "judgments-ahkaam"],
    [94, "كتاب التمنى", "Wishes", "wishes"],
    [95, "كتاب أخبار الآحاد", "Accepting Information Given by a Truthful Person", "accepting-information-given-by-a-truthful-person"],
    [96, "كتاب الاعتصام بالكتاب والسنة", "Holding Fast to the Qur'an and Sunnah", "holding-fast-to-the-quran-and-sunnah"],
    [97, "كتاب التوحيد", "Oneness, Uniqueness of Allah (Tawheed)", "oneness-uniqueness-of-allah-tawheed"],
  ],
  muslim: [
    [0, "المقدمة", "Introduction", "introduction"],
    [1, "كتاب الإيمان", "The Book of Faith", "book-of-faith"],
    [2, "كتاب الطهارة", "The Book of Purification", "book-of-purification"],
    [3, "كتاب الحيض", "The Book of Menstruation", "book-of-menstruation"],
    [4, "كتاب الصلاة", "The Book of Prayers", "book-of-prayers"],
    [5, "كتاب الْمَسَاجِدِ وَمَوَاضِعِ الصَّلاَةِ", "The Book of Mosques and Places of Prayer", "book-of-mosques-and-places-of-prayer"],
    [6, "كتاب صلاة المسافرين وقصرها", "The Book of Prayer - Travellers", "book-of-prayer-travellers"],
    [7, "كتاب الجمعة", "The Book of Prayer - Friday", "book-of-prayer-friday"],
    [8, "كتاب صلاة العيدين", "The Book of Prayer - Two Eids", "book-of-prayer-two-eids"],
    [9, "كتاب صلاة الاستسقاء‏", "The Book of Prayer - Rain", "book-of-prayer-rain"],
    [10, "كتاب الكسوف", "The Book of Prayer - Eclipses", "book-of-prayer-eclipses"],
    [11, "كتاب الجنائز", "The Book of Prayer - Funerals", "book-of-prayer-funerals"],
    [12, "كتاب الزكاة", "The Book of Zakat", "book-of-zakat"],
    [13, "كتاب الصيام", "The Book of Fasting", "book-of-fasting"],
    [14, "كتاب الاعتكاف", "The Book of I'tikaf", "book-of-itikaf"],
    [15, "كتاب الحج", "The Book of Pilgrimage", "book-of-pilgrimage"],
    [16, "كتاب النكاح", "The Book of Marriage", "book-of-marriage"],
    [17, "كتاب الرضاع", "The Book of Suckling", "book-of-suckling"],
    [18, "كتاب الطلاق", "The Book of Divorce", "book-of-divorce"],
    [19, "كتاب اللعان", "The Book of Invoking Curses", "book-of-invoking-curses"],
    [20, "كتاب العتق", "The Book of Emancipating Slaves", "book-of-emancipating-slaves"],
    [21, "كتاب البيوع", "The Book of Transactions", "book-of-transactions"],
    [22, "كتاب المساقاة", "The Book of Musaqah", "book-of-musaqah"],
    [23, "كتاب الفرائض", "The Book of the Rules of Inheritance", "book-of-the-rules-of-inheritance"],
    [24, "كتاب الهبات", "The Book of Gifts", "book-of-gifts"],
    [25, "كتاب الوصية", "The Book of Wills", "book-of-wills"],
    [26, "كتاب النذر", "The Book of Vows", "book-of-vows"],
    [27, "كتاب الأيمان", "The Book of Oaths", "book-of-oaths"],
    [28, "كتاب القسامة والمحاربين والقصاص والديات", "The Book of Oaths, Muharibin, Qasas (Retaliation), and Diyat (Blood Money)", "book-of-oaths-muharibin-qasas-retaliation-and-diyat-blood"],
    [29, "كتاب الحدود", "The Book of Legal Punishments", "book-of-legal-punishments"],
    [30, "كتاب الأقضية", "The Book of Judicial Decisions", "book-of-judicial-decisions"],
    [31, "كتاب اللقطة", "The Book of Lost Property", "book-of-lost-property"],
    [32, "كتاب الجهاد والسير", "The Book of Jihad and Expeditions", "book-of-jihad-and-expeditions"],
    [33, "كتاب الإمارة", "The Book on Government", "book-on-government"],
    [34, "كتاب الصيد والذبائح وما يؤكل من الحيوان", "The Book of Hunting, Slaughter, and what may be Eaten", "book-of-hunting-slaughter-and-what-may-be-eaten"],
    [35, "كتاب الأضاحى", "The Book of Sacrifices", "book-of-sacrifices"],
    [36, "كتاب الأشربة", "The Book of Drinks", "book-of-drinks"],
    [37, "كتاب اللباس والزينة", "The Book of Clothes and Adornment", "book-of-clothes-and-adornment"],
    [38, "كتاب الآداب", "The Book of Manners and Etiquette", "book-of-manners-and-etiquette"],
    [39, "كتاب السلام", "The Book of Greetings", "book-of-greetings"],
    [40, "كتاب الألفاظ من الأدب وغيرها", "The Book Concerning the Use of Correct Words", "book-concerning-the-use-of-correct-words"],
    [41, "كتاب الشعر", "The Book of Poetry", "book-of-poetry"],
    [42, "كتاب الرؤيا", "The Book of Dreams", "book-of-dreams"],
    [43, "كتاب الفضائل", "The Book of Virtues", "book-of-virtues"],
    [44, "كتاب فضائل الصحابة رضى الله تعالى عنهم", "The Book of the Merits of the Companions", "book-of-the-merits-of-the-companions"],
    [45, "كتاب البر والصلة والآداب", "The Book of Virtue, Enjoining Good Manners, and Joining of the Ties of Kinship", "book-of-virtue-enjoining-good-manners-and-joining-of-the"],
    [46, "كتاب القدر", "The Book of Destiny", "book-of-destiny"],
    [47, "كتاب العلم", "The Book of Knowledge", "book-of-knowledge"],
    [48, "كتاب الذكر والدعاء والتوبة والاستغفار", "The Book Pertaining to the Remembrance of Allah, Supplication, Repentance and Seeking Forgiveness", "book-pertaining-to-the-remembrance-of-allah-supplication"],
    [49, "كتاب الرقاق", "The Book of Heart-Melting Traditions", "book-of-heart-melting-traditions"],
    [50, "كتاب التوبة", "The Book of Repentance", "book-of-repentance"],
    [51, "كتاب صفات المنافقين وأحكامهم", "Characteristics of The Hypocrites And Rulings Concerning Them", "characteristics-of-the-hypocrites-and-rulings-concerning"],
    [52, "كتاب صفة القيامة والجنة والنار", "Characteristics of the Day of Judgment, Paradise, and Hell", "characteristics-of-the-day-of-judgment-paradise-and-hell"],
    [53, "كتاب الجنة وصفة نعيمها وأهلها", "The Book of Paradise, its Description, its Bounties and its Inhabitants", "book-of-paradise-its-description-its-bounties-and-its"],
    [54, "كتاب الفتن وأشراط الساعة", "The Book of Tribulations and Portents of the Last Hour", "book-of-tribulations-and-portents-of-the-last-hour"],
    [55, "كتاب الزهد والرقائق", "The Book of Zuhd and Softening of Hearts", "book-of-zuhd-and-softening-of-hearts"],
    [56, "كتاب التفسير", "The Book of Commentary on the Qur'an", "book-of-commentary-on-the-quran"],
  ],
  abudawud: [
    [1, "كتاب الطهارة", "Purification (Kitab Al-Taharah)", "purification-kitab-al-taharah"],
    [2, "كتاب الصلاة", "Prayer (Kitab Al-Salat)", "prayer-kitab-al-salat"],
    [3, "كتاب الاستسقاء", "The Book Of The Prayer For Rain (Kitab al-Istisqa')", "book-of-the-prayer-for-rain-kitab-al-istisqa"],
    [4, "كتاب صلاة السفر", "Prayer (Kitab Al-Salat): Detailed Rules of Law about the Prayer during Journey", "prayer-kitab-al-salat-detailed-rules-of-law-about-the-prayer"],
    [5, "كتاب التطوع", "Prayer (Kitab Al-Salat): Voluntary Prayers", "prayer-kitab-al-salat-voluntary-prayers"],
    [6, "كتاب شهر رمضان", "Prayer (Kitab Al-Salat): Detailed Injunctions about Ramadan", "prayer-kitab-al-salat-detailed-injunctions-about-ramadan"],
    [7, "كتاب سجود القرآن", "Prayer (Kitab Al-Salat): Prostration while reciting the Qur'an", "prayer-kitab-al-salat-prostration-while-reciting-the-quran"],
    [8, "كتاب الوتر", "Prayer (Kitab Al-Salat): Detailed Injunctions about Witr", "prayer-kitab-al-salat-detailed-injunctions-about-witr"],
    [9, "كتاب الزكاة", "Zakat (Kitab Al-Zakat)", "zakat-kitab-al-zakat"],
    [10, "كتاب اللقطة", "The Book of Lost and Found Items", "book-of-lost-and-found-items"],
    [11, "كتاب المناسك", "The Rites of Hajj (Kitab Al-Manasik Wa'l-Hajj)", "rites-of-hajj-kitab-al-manasik-wal-hajj"],
    [12, "كتاب النكاح", "Marriage (Kitab Al-Nikah)", "marriage-kitab-al-nikah"],
    [13, "كتاب الطلاق", "Divorce (Kitab Al-Talaq)", "divorce-kitab-al-talaq"],
    [14, "كتاب الصوم", "Fasting (Kitab Al-Siyam)", "fasting-kitab-al-siyam"],
    [15, "كتاب الجهاد", "Jihad (Kitab Al-Jihad)", "jihad-kitab-al-jihad"],
    [16, "كتاب الضحايا", "Sacrifice (Kitab Al-Dahaya)", "sacrifice-kitab-al-dahaya"],
    [17, "كتاب الصيد", "Game (Kitab Al-Said)", "game-kitab-al-said"],
    [18, "كتاب الوصايا", "Wills (Kitab Al-Wasaya)", "wills-kitab-al-wasaya"],
    [19, "كتاب الفرائض", "Shares of Inheritance (Kitab Al-Fara'id)", "shares-of-inheritance-kitab-al-faraid"],
    [20, "كتاب الخراج والإمارة والفىء", "Tribute, Spoils, and Rulership (Kitab Al-Kharaj, Wal-Fai' Wal-Imarah)", "tribute-spoils-and-rulership-kitab-al-kharaj-wal-fai-wal"],
    [21, "كتاب الجنائز", "Funerals (Kitab Al-Jana'iz)", "funerals-kitab-al-janaiz"],
    [22, "كتاب الأيمان والنذور", "Oaths and Vows (Kitab Al-Aiman Wa Al-Nudhur)", "oaths-and-vows-kitab-al-aiman-wa-al-nudhur"],
    [23, "كتاب البيوع", "Commercial Transactions (Kitab Al-Buyu)", "commercial-transactions-kitab-al-buyu"],
    [24, "كتاب الإجارة", "Wages (Kitab Al-Ijarah)", "wages-kitab-al-ijarah"],
    [25, "كتاب الأقضية", "The Office of the Judge (Kitab Al-Aqdiyah)", "office-of-the-judge-kitab-al-aqdiyah"],
    [26, "كتاب العلم", "Knowledge (Kitab Al-Ilm)", "knowledge-kitab-al-ilm"],
    [27, "كتاب الأشربة", "Drinks (Kitab Al-Ashribah)", "drinks-kitab-al-ashribah"],
    [28, "كتاب الأطعمة", "Foods (Kitab Al-At'imah)", "foods-kitab-al-atimah"],
    [29, "كتاب الطب", "Medicine (Kitab Al-Tibb)", "medicine-kitab-al-tibb"],
    [30, "كتاب الكهانة و التطير", "Divination and Omens (Kitab Al-Kahanah Wa Al-Tatayyur)", "divination-and-omens-kitab-al-kahanah-wa-al-tatayyur"],
    [31, "كتاب العتق", "The Book of Manumission of Slaves", "book-of-manumission-of-slaves"],
    [32, "كتاب الحروف والقراءات", "Dialects and Readings of the Qur'an (Kitab Al-Huruf Wa Al-Qira'at)", "dialects-and-readings-of-the-quran-kitab-al-huruf-wa-al"],
    [33, "كتاب الحمَّام", "Hot Baths (Kitab Al-Hammam)", "hot-baths-kitab-al-hammam"],
    [34, "كتاب اللباس", "Clothing (Kitab Al-Libas)", "clothing-kitab-al-libas"],
    [35, "كتاب الترجل", "Combing the Hair (Kitab Al-Tarajjul)", "combing-the-hair-kitab-al-tarajjul"],
    [36, "كتاب الخاتم", "Signet-Rings (Kitab Al-Khatam)", "signet-rings-kitab-al-khatam"],
    [37, "كتاب الفتن والملاحم", "Trials and Fierce Battles (Kitab Al-Fitan Wa Al-Malahim)", "trials-and-fierce-battles-kitab-al-fitan-wa-al-malahim"],
    [38, "كتاب المهدى", "The Promised Deliverer (Kitab Al-Mahdi)", "promised-deliverer-kitab-al-mahdi"],
    [39, "كتاب الملاحم", "Battles (Kitab Al-Malahim)", "battles-kitab-al-malahim"],
    [40, "كتاب الحدود", "Prescribed Punishments (Kitab Al-Hudud)", "prescribed-punishments-kitab-al-hudud"],
    [41, "كتاب الديات", "Types of Blood-Wit (Kitab Al-Diyat)", "types-of-blood-wit-kitab-al-diyat"],
    [42, "كتاب السنة", "Model Behavior of the Prophet (Kitab Al-Sunnah)", "model-behavior-of-the-prophet-kitab-al-sunnah"],
    [43, "كتاب الأدب", "General Behavior (Kitab Al-Adab)", "general-behavior-kitab-al-adab"],
  ],
  tirmidhi: [
    [1, "كتاب الطهارة عن رسول الله صلى الله عليه وسلم", "The Book on Purification", "book-on-purification"],
    [2, "كتاب الصلاة", "The Book on Salat (Prayer)", "book-on-salat-prayer"],
    [3, "أَبْوَابُ الْوِتْرِ", "The Book on Al-Witr", "book-on-al-witr"],
    [4, "كِتَاب الْجُمُعَةِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ", "The Book on the Day of Friday", "book-on-the-day-of-friday"],
    [5, "أَبْوَابُ الْعِيدَيْنِ عَنْ رَسُولِ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ", "The Book on the Two Eids", "book-on-the-two-eids"],
    [6, "أَبْوَابُ السَّفَرِ", "The Book on Traveling", "book-on-traveling"],
    [7, "كتاب الزكاة عن رسول الله صلى الله عليه وسلم", "The Book on Zakat", "book-on-zakat"],
    [8, "كتاب الصوم عن رسول الله صلى الله عليه وسلم", "The Book on Fasting", "book-on-fasting"],
    [9, "كتاب الحج عن رسول الله صلى الله عليه وسلم", "The Book on Hajj", "book-on-hajj"],
    [10, "كتاب الجنائز عن رسول الله صلى الله عليه وسلم", "The Book on Jana''iz (Funerals)", "book-on-janaiz-funerals"],
    [11, "كتاب النكاح عن رسول الله صلى الله عليه وسلم", "The Book on Marriage", "book-on-marriage"],
    [12, "كتاب الرضاع", "The Book on Suckling", "book-on-suckling"],
    [13, "كتاب الطلاق واللعان عن رسول الله صلى الله عليه وسلم", "The Book on Divorce and Li'an", "book-on-divorce-and-lian"],
    [14, "كتاب البيوع عن رسول الله صلى الله عليه وسلم", "The Book on Business", "book-on-business"],
    [15, "كتاب الأحكام عن رسول الله صلى الله عليه وسلم", "The Chapters On Judgements From The Messenger of Allah", "chapters-on-judgements-from-the-messenger-of-allah"],
    [16, "كتاب الديات عن رسول الله صلى الله عليه وسلم", "The Book on Blood Money", "book-on-blood-money"],
    [17, "كتاب الحدود عن رسول الله صلى الله عليه وسلم", "The Book on Legal Punishments (Al-Hudud)", "book-on-legal-punishments-al-hudud"],
    [18, "كتاب الصيد والذبائح عن رسول الله صلى الله عليه وسلم", "The Book on Hunting", "book-on-hunting"],
    [19, "كتاب الأضاحى عن رسول الله صلى الله عليه وسلم", "The Book on Sacrifices", "book-on-sacrifices"],
    [20, "كتاب النذور والأيمان عن رسول الله صلى الله عليه وسلم", "The Book on Vows and Oaths", "book-on-vows-and-oaths"],
    [21, "كتاب السير عن رسول الله صلى الله عليه وسلم", "The Book on Military Expeditions", "book-on-military-expeditions"],
    [22, "كتاب فضائل الجهاد عن رسول الله صلى الله عليه وسلم", "The Book on Virtues of Jihad", "book-on-virtues-of-jihad"],
    [23, "كتاب الجهاد عن رسول الله صلى الله عليه وسلم", "The Book on Jihad", "book-on-jihad"],
    [24, "كتاب اللباس", "The Book on Clothing", "book-on-clothing"],
    [25, "كتاب الأطعمة عن رسول الله صلى الله عليه وسلم", "The Book on Food", "book-on-food"],
    [26, "كتاب الأشربة عن رسول الله صلى الله عليه وسلم", "The Book on Drinks", "book-on-drinks"],
    [27, "كتاب البر والصلة عن رسول الله صلى الله عليه وسلم", "Chapters on Righteousness And Maintaining Good Relations With Relatives", "chapters-on-righteousness-and-maintaining-good-relations"],
    [28, "كتاب الطب عن رسول اللَّهِ صلى الله عليه وسلم", "Chapters on Medicine", "chapters-on-medicine"],
    [29, "كتاب الفرائض عن رسول الله صلى الله عليه وسلم", "Chapters On Inheritance", "chapters-on-inheritance"],
    [30, "كتاب الوصايا عن رسول الله صلى الله عليه وسلم", "Chapters On Wasaya (Wills and Testament)", "chapters-on-wasaya-wills-and-testament"],
    [31, "كتاب الولاء والهبة عن رسول الله صلى الله عليه وسلم", "Chapters On Wala' And Gifts", "chapters-on-wala-and-gifts"],
    [32, "كتاب القدر عن رسول الله صلى الله عليه وسلم", "Chapters On Al-Qadar", "chapters-on-al-qadar"],
    [33, "كتاب الفتن عن رسول الله صلى الله عليه وسلم", "Chapters On Al-Fitan", "chapters-on-al-fitan"],
    [34, "كتاب الرؤيا عن رسول الله صلى الله عليه وسلم", "Chapters On Dreams", "chapters-on-dreams"],
    [35, "كتاب الشهادات عن رسول الله صلى الله عليه وسلم", "Chapters On Witnesses", "chapters-on-witnesses"],
    [36, "كتاب الزهد عن رسول الله صلى الله عليه وسلم", "Chapters On Zuhd", "chapters-on-zuhd"],
    [37, "كتاب صفة القيامة والرقائق والورع عن رسول الله صلى الله", "Chapters on the description of the Day of Judgement, Ar-Riqaq, and Al-Wara'", "chapters-on-the-description-of-the-day-of-judgement-ar-riqaq"],
    [38, "كتاب صفة الجنة عن رسول الله صلى الله عليه وسلم", "Chapters on the description of Paradise", "chapters-on-the-description-of-paradise"],
    [39, "كتاب صفة جهنم عن رسول الله صلى الله عليه وسلم", "The Book on the Description of Hellfire", "book-on-the-description-of-hellfire"],
    [40, "كتاب الإيمان عن رسول الله صلى الله عليه وسلم", "The Book on Faith", "book-on-faith"],
    [41, "كتاب العلم عن رسول الله صلى الله عليه وسلم", "Chapters on Knowledge", "chapters-on-knowledge"],
    [42, "كتاب الاستئذان والآداب عن رسول الله صلى الله عليه وسلم", "Chapters on Seeking Permission", "chapters-on-seeking-permission"],
    [43, "كتاب الأدب عن رسول الله صلى الله عليه وسلم", "Chapters on Manners", "chapters-on-manners"],
    [44, "كتاب الأمثال عن رسول الله صلى الله عليه وسلم", "Chapters on Parables", "chapters-on-parables"],
    [45, "كتاب ثواب القرآن عن رسول الله صلى الله عليه وسلم", "Chapters on The Virtues of the Qur'an", "chapters-on-the-virtues-of-the-quran"],
    [46, "كتاب القراءات عن رسول الله صلى الله عليه وسلم", "Chapters on Recitation", "chapters-on-recitation"],
    [47, "كتاب تفسير القرآن عن رسول الله صلى الله عليه وسلم", "Chapters on Tafsir", "chapters-on-tafsir"],
    [48, "كتاب الدعوات عن رسول الله صلى الله عليه وسلم", "Chapters on Supplication", "chapters-on-supplication"],
    [49, "كتاب المناقب عن رسول الله صلى الله عليه وسلم", "Chapters on Virtues", "chapters-on-virtues"],
  ],
  nasai: [
    [1, "كتاب الطهارة", "The Book of Purification", "book-of-purification"],
    [2, "كتاب المياه", "The Book of Water", "book-of-water"],
    [3, "كتاب الحيض والاستحاضة", "The Book of Menstruation and Istihadah", "book-of-menstruation-and-istihadah"],
    [4, "كتاب الغسل والتيمم", "The Book of Ghusl and Tayammum", "book-of-ghusl-and-tayammum"],
    [5, "كتاب الصلاة", "The Book of Salah", "book-of-salah"],
    [6, "كتاب المواقيت", "The Book of the Times (of Prayer)", "book-of-the-times-of-prayer"],
    [7, "كتاب الأذان", "The Book of the Adhan (The Call to Prayer)", "book-of-the-adhan-the-call-to-prayer"],
    [8, "كتاب المساجد", "The Book of the Masjids", "book-of-the-masjids"],
    [9, "كتاب القبلة", "The Book of the Qiblah", "book-of-the-qiblah"],
    [10, "كتاب الإمامة", "The Book of Leading the Prayer (Al-Imamah)", "book-of-leading-the-prayer-al-imamah"],
    [11, "كتاب الافتتاح", "The Book of the Commencement of the Prayer", "book-of-the-commencement-of-the-prayer"],
    [12, "كتاب التطبيق", "The Book of The At-Tatbiq (Clasping One's Hands Together)", "book-of-the-at-tatbiq-clasping-ones-hands-together"],
    [13, "كتاب السهو", "The Book of Forgetfulness (In Prayer)", "book-of-forgetfulness-in-prayer"],
    [14, "كتاب الجمعة", "The Book of Jumu'ah (Friday Prayer)", "book-of-jumuah-friday-prayer"],
    [15, "كتاب تقصير الصلاة فى السفر", "The Book of Shortening the Prayer When Traveling", "book-of-shortening-the-prayer-when-traveling"],
    [16, "كتاب الكسوف", "The Book of Eclipses", "book-of-eclipses"],
    [17, "كتاب الاستسقاء", "The Book of Praying for Rain (Al-Istisqa')", "book-of-praying-for-rain-al-istisqa"],
    [18, "كتاب صلاة الخوف", "The Book of the Fear Prayer", "book-of-the-fear-prayer"],
    [19, "كتاب صلاة العيدين", "The Book of the Prayer for the Two 'Eids", "book-of-the-prayer-for-the-two-eids"],
    [20, "كتاب قيام الليل وتطوع النهار", "The Book of Qiyam Al-Lail (The Night Prayer) and Voluntary Prayers During the Day", "book-of-qiyam-al-lail-the-night-prayer-and-voluntary-prayers"],
    [21, "كتاب الجنائز", "The Book of Funerals", "book-of-funerals"],
    [22, "كتاب الصيام", "The Book of Fasting", "book-of-fasting"],
    [23, "كتاب الزكاة", "The Book of Zakah", "book-of-zakah"],
    [24, "كتاب مناسك الحج", "The Book of Hajj", "book-of-hajj"],
    [25, "كتاب الجهاد", "The Book of Jihad", "book-of-jihad"],
    [26, "كتاب النكاح", "The Book of Marriage", "book-of-marriage"],
    [27, "كتاب الطلاق", "The Book of Divorce", "book-of-divorce"],
    [28, "كتاب الخيل", "The Book of Horses, Races and Shooting", "book-of-horses-races-and-shooting"],
    [29, "كتاب الإحباس", "The Book of Endowments", "book-of-endowments"],
    [30, "كتاب الوصايا", "The Book of Wills", "book-of-wills"],
    [31, "كتاب النحل", "The Book of Presents", "book-of-presents"],
    [32, "كتاب الهبة", "The Book of Gifts", "book-of-gifts"],
    [33, "كتاب الرقبى", "The Book of ar-Ruqba", "book-of-ar-ruqba"],
    [34, "كتاب العمرى", "The Book of 'Umra", "book-of-umra"],
    [35, "كتاب المزارعة", "The Book of Agriculture", "book-of-agriculture"],
    [36, "كتاب عشرة النساء", "The Book of the Kind Treatment of Women", "book-of-the-kind-treatment-of-women"],
    [37, "كتاب تحريم الدم", "The Book of Fighting [The Prohibition of Bloodshed]", "book-of-fighting-the-prohibition-of-bloodshed"],
    [38, "كتاب قسم الفىء", "The Book of Distribution of Al-Fay'", "book-of-distribution-of-al-fay"],
    [39, "كتاب البيعة", "The Book of al-Bay'ah", "book-of-al-bayah"],
    [40, "كتاب العقيقة", "The Book of al-'Aqiqah", "book-of-al-aqiqah"],
    [41, "كتاب الفرع والعتيرة", "The Book of al-Fara' and al-'Atirah", "book-of-al-fara-and-al-atirah"],
    [42, "كتاب الصيد والذبائح", "The Book of Hunting and Slaughtering", "book-of-hunting-and-slaughtering"],
    [43, "كتاب الضحايا", "The Book of ad-Dahaya (Sacrifices)", "book-of-ad-dahaya-sacrifices"],
    [44, "كتاب البيوع", "The Book of Financial Transactions", "book-of-financial-transactions"],
    [45, "كتاب القسامة", "The Book of Oaths (qasamah), Retaliation and Blood Money", "book-of-oaths-qasamah-retaliation-and-blood-money"],
    [46, "كتاب قطع السارق", "The Book of Cutting off the Hand of the Thief", "book-of-cutting-off-the-hand-of-the-thief"],
    [47, "كتاب الإيمان وشرائعه", "The Book Of Faith and its Signs", "book-of-faith-and-its-signs"],
    [48, "كتاب الزينة من السنن", "The Book of Adornment", "book-of-adornment"],
    [49, "كتاب آداب القضاة", "The Book of the Etiquette of Judges", "book-of-the-etiquette-of-judges"],
    [50, "كتاب الاستعاذة", "The Book of Seeking Refuge with Allah", "book-of-seeking-refuge-with-allah"],
    [51, "كتاب الأشربة", "The Book of Drinks", "book-of-drinks"],
  ],
  ibnmajah: [
    [0, "كتاب السنة", "The Book of the Sunnah", "book-of-the-sunnah"],
    [1, "كتاب الطهارة وسننها", "The Book of Purification and its Sunnah", "book-of-purification-and-its-sunnah"],
    [2, "كتاب الصلاة", "The Book of the Prayer", "book-of-the-prayer"],
    [3, "كتاب الأذان والسنة فيها", "The Book of the Adhan and the Sunnah Regarding It", "book-of-the-adhan-and-the-sunnah-regarding-it"],
    [4, "كتاب المساجد والجماعات", "The Book On The Mosques And The Congregations", "book-on-the-mosques-and-the-congregations"],
    [5, "كتاب إقامة الصلاة والسنة فيها", "Establishing the Prayer and the Sunnah Regarding Them", "establishing-the-prayer-and-the-sunnah-regarding-them"],
    [6, "كتاب الجنائز", "Chapters Regarding Funerals", "chapters-regarding-funerals"],
    [7, "كتاب الصيام", "Fasting", "fasting"],
    [8, "كتاب الزكاة", "The Chapters Regarding Zakat", "chapters-regarding-zakat"],
    [9, "كتاب النكاح", "The Chapters on Marriage", "chapters-on-marriage"],
    [10, "كتاب الطلاق", "The Chapters on Divorce", "chapters-on-divorce"],
    [11, "كتاب الكفارات", "The Chapters on Expiation", "chapters-on-expiation"],
    [12, "كتاب التجارات", "The Chapters on Business Transactions", "chapters-on-business-transactions"],
    [13, "كتاب الأحكام", "The Chapters on Rulings", "chapters-on-rulings"],
    [14, "كتاب الهبات", "The Chapters on Gifts", "chapters-on-gifts"],
    [15, "كتاب الصدقات", "The Chapters on Charity", "chapters-on-charity"],
    [16, "كتاب الرهون", "The Chapters on Pawning", "chapters-on-pawning"],
    [17, "كتاب الشفعة", "The Chapters on Pre-emption", "chapters-on-pre-emption"],
    [18, "كتاب اللقطة", "The Chapters on Lost Property", "chapters-on-lost-property"],
    [19, "كتاب العتق", "The Chapters on Manumission (of Slaves)", "chapters-on-manumission-of-slaves"],
    [20, "كتاب الحدود", "The Chapters on Legal Punishments", "chapters-on-legal-punishments"],
    [21, "كتاب الديات", "The Chapters on Blood Money", "chapters-on-blood-money"],
    [22, "كتاب الوصايا", "The Chapters on Wills", "chapters-on-wills"],
    [23, "كتاب الفرائض", "Chapters on Shares of Inheritance", "chapters-on-shares-of-inheritance"],
    [24, "كتاب الجهاد", "The Chapters on Jihad", "chapters-on-jihad"],
    [25, "كتاب المناسك", "Chapters on Hajj Rituals", "chapters-on-hajj-rituals"],
    [26, "كتاب الأضاحي", "Chapters on Sacrifices", "chapters-on-sacrifices"],
    [27, "كتاب الذبائح", "Chapters on Slaughtering", "chapters-on-slaughtering"],
    [28, "كتاب الصيد", "Chapters on Hunting", "chapters-on-hunting"],
    [29, "كتاب الأطعمة", "Chapters on Food", "chapters-on-food"],
    [30, "كتاب الأشربة", "Chapters on Drinks", "chapters-on-drinks"],
    [31, "كتاب الطب", "Chapters on Medicine", "chapters-on-medicine"],
    [32, "كتاب اللباس", "Chapters on Dress", "chapters-on-dress"],
    [33, "كتاب الأدب", "Etiquette", "etiquette"],
    [34, "كتاب الدعاء", "Supplication", "supplication"],
    [35, "كتاب تعبير الرؤيا", "Interpretation of Dreams", "interpretation-of-dreams"],
    [36, "كتاب الفتن", "Tribulations", "tribulations"],
    [37, "كتاب الزهد", "Zuhd", "zuhd"],
  ],
  malik: [
    [1, "كتاب وقوت الصلاة", "The Times of Prayer", "times-of-prayer"],
    [2, "كتاب الطهارة", "Purity", "purity"],
    [3, "كتاب الصلاة", "Prayer", "prayer"],
    [4, "كتاب السهو", "Forgetfulness in Prayer", "forgetfulness-in-prayer"],
    [5, "كتاب الجمعة", "Jumu'a", "jumua"],
    [6, "كتاب الصلاة فى رمضان", "Prayer in Ramadan", "prayer-in-ramadan"],
    [7, "كتاب صلاة الليل", "Tahajjud", "tahajjud"],
    [8, "كتاب صلاة الجماعة", "Prayer in Congregation", "prayer-in-congregation"],
    [9, "كتاب قصر الصلاة فى السفر", "Shortening the Prayer", "shortening-the-prayer"],
    [10, "كتاب العيدين", "The Two 'Ids", "two-ids"],
    [11, "كتاب صلاة الخوف", "The Fear Prayer", "fear-prayer"],
    [12, "كتاب صلاة الكسوف", "The Eclipse Prayer", "eclipse-prayer"],
    [13, "كتاب الاستسقاء", "Asking for Rain", "asking-for-rain"],
    [14, "كتاب القبلة", "The Qibla", "qibla"],
    [15, "كتاب القرآن", "The Qur'an", "quran"],
    [16, "كتاب الجنائز", "Burials", "burials"],
    [17, "كتاب الزكاة", "Zakat", "zakat"],
    [18, "كتاب الصيام", "Fasting", "fasting"],
    [19, "كتاب الاعتكاف", "I'tikaf in Ramadan", "itikaf-in-ramadan"],
    [20, "كتاب الحج", "Hajj", "hajj"],
    [21, "كتاب الجهاد", "Jihad", "jihad"],
    [22, "كتاب النذور والأيمان", "Vows and Oaths", "vows-and-oaths"],
    [23, "كتاب الضحايا", "Sacrificial Animals", "sacrificial-animals"],
    [24, "كتاب الذبائح", "Slaughtering Animals", "slaughtering-animals"],
    [25, "كتاب الصيد", "Game", "game"],
    [26, "كتاب العقيقة", "The 'Aqiqa", "aqiqa"],
    [27, "كتاب الفرائض", "Fara'id", "faraid"],
    [28, "كتاب النكاح", "Marriage", "marriage"],
    [29, "كتاب الطلاق", "Divorce", "divorce"],
    [30, "كتاب الرضاع", "Suckling", "suckling"],
    [31, "كتاب البيوع", "Business Transactions", "business-transactions"],
    [32, "كتاب القراض", "Qirad", "qirad"],
    [33, "كتاب المساقاة", "Sharecropping", "sharecropping"],
    [34, "كتاب كراء الأرض", "Renting Land", "renting-land"],
    [35, "كتاب الشفعة", "Pre-emption in Property", "pre-emption-in-property"],
    [36, "كتاب الأقضية", "Judgements", "judgements"],
    [37, "كتاب الوصية", "Wills and Testaments", "wills-and-testaments"],
    [38, "كتاب العتق والولاء", "Setting Free and Wala'", "setting-free-and-wala"],
    [39, "كتاب المكاتب", "The Mukatab", "mukatab"],
    [40, "كتاب المدبر", "The Mudabbar", "mudabbar"],
    [41, "كتاب الحدود", "Hudud", "hudud"],
    [42, "كتاب الأشربة", "Drinks", "drinks"],
    [43, "كتاب العقول", "Blood-Money", "blood-money"],
    [44, "كتاب القسامة", "The Oath of Qasama", "oath-of-qasama"],
    [45, "كتاب الْمَدِينَةِ", "Madina", "madina"],
    [46, "كتاب القدر", "The Decree", "decree"],
    [47, "كتاب حسن الخلق", "Good Character", "good-character"],
    [48, "كتاب اللباس", "Dress", "dress"],
    [49, "كتاب صفة النبى صلى الله عليه وسلم", "The Description of the Prophet, may Allah Bless Him and Grant Him Peace", "description-of-the-prophet-may-allah-bless-him-and-grant-him"],
    [50, "كتاب العين", "The Evil Eye", "evil-eye"],
    [51, "كتاب الشعر", "Hair", "hair"],
    [52, "كتاب الرؤيا", "Visions", "visions"],
    [53, "كتاب السلام", "Greetings", "greetings"],
    [54, "كتاب الاستئذان", "General Subjects", "general-subjects"],
    [55, "كتاب البيعة", "The Oath of Allegiance", "oath-of-allegiance"],
    [56, "كتاب الكلام", "Speech", "speech"],
    [57, "كتاب جهنم", "Jahannam", "jahannam"],
    [58, "كتاب الصدقة", "Sadaqa", "sadaqa"],
    [59, "كتاب العلم", "Knowledge", "knowledge"],
    [60, "كتاب دعوة المظلوم", "The Supplication of the Unjustly Wronged", "supplication-of-the-unjustly-wronged"],
    [61, "كتاب أسماء النبى صلى الله عليه وسلم", "The Names of the Prophet, may Allah Bless Him and Grant Him Peace", "names-of-the-prophet-may-allah-bless-him-and-grant-him-peace"],
  ],
  nawawi: [
    [1, "الأربعون النووية", "The Forty Hadith", "forty-hadith"],
  ],
  qudsi: [
    [1, "الأربعون القدسية", "The Forty Hadith Qudsi", "forty-hadith-qudsi"],
  ],
  dehlawi: [
    [1, "الأربعون للشاه ولي الله الدهلوي", "The Forty Hadith", "forty-hadith"],
  ],
};
