export type DivineName = {
  arabic: string;
  transliteration: string;
  /** Short English rendering of the name. */
  meaning: string;
  /** Short Arabic gloss of the name's meaning. */
  meaningAr: string;
  /** A one-sentence explanation, following mainstream Sunni understanding. */
  explanation: string;
};

/** Al-Asma ul-Husna — the 99 beautiful names of Allah, each with a short
 * meaning and a concise explanation. Embedded so the tool works fully offline. */
export const NAMES_OF_ALLAH: DivineName[] = [
  { arabic: "الرَّحْمَنُ", transliteration: "Ar-Rahman", meaning: "The Most Merciful", meaningAr: "ذو الرحمة الواسعة لكل الخلق", explanation: "The One whose boundless mercy encompasses all of creation in this world." },
  { arabic: "الرَّحِيمُ", transliteration: "Ar-Rahim", meaning: "The Bestower of Mercy", meaningAr: "الرحيم بالمؤمنين", explanation: "The One who is especially and eternally merciful to the believers." },
  { arabic: "الْمَلِكُ", transliteration: "Al-Malik", meaning: "The King", meaningAr: "المالك المتصرف في كل شيء", explanation: "The absolute Sovereign who owns and governs all dominion." },
  { arabic: "الْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy", meaningAr: "المنزَّه عن كل نقص", explanation: "The One utterly pure and free from every flaw and imperfection." },
  { arabic: "السَّلَامُ", transliteration: "As-Salam", meaning: "The Source of Peace", meaningAr: "السالم من العيوب ومصدر السلام", explanation: "The One free of all defects, from whom safety and peace flow." },
  { arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Giver of Security", meaningAr: "واهب الأمان المصدِّق", explanation: "The One who grants security and confirms the truth of His messengers." },
  { arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Guardian", meaningAr: "الرقيب الحافظ على خلقه", explanation: "The Overseer who watches over and safeguards all things." },
  { arabic: "الْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Almighty", meaningAr: "القوي الذي لا يُغلب", explanation: "The mighty and invincible One who is never overcome." },
  { arabic: "الْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller", meaningAr: "القاهر الذي نفذت مشيئته", explanation: "The One whose will prevails over all, who mends and restores." },
  { arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Supreme in Greatness", meaningAr: "المتعالي عن صفات الخلق", explanation: "The One rightfully supreme, exalted above every creation." },
  { arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator", meaningAr: "الموجِد للخلق من العدم", explanation: "The One who brings all things into existence from nothing." },
  { arabic: "الْبَارِئُ", transliteration: "Al-Bari'", meaning: "The Originator", meaningAr: "المنشئ للخلق بلا تفاوت", explanation: "The One who fashions creation free of fault, in perfect proportion." },
  { arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner", meaningAr: "المصوِّر لخلقه كيف شاء", explanation: "The One who gives every creation its distinct form and shape." },
  { arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The All-Forgiving", meaningAr: "كثير المغفرة لعباده", explanation: "The One who repeatedly forgives the sins of His servants." },
  { arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer", meaningAr: "الغالب لكل شيء بقهره", explanation: "The One who dominates all creation by His irresistible power." },
  { arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower", meaningAr: "كثير العطاء بلا مقابل", explanation: "The One who gives freely and continuously, expecting nothing in return." },
  { arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Provider", meaningAr: "الرازق لجميع خلقه", explanation: "The One who provides sustenance for every living creature." },
  { arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener", meaningAr: "الفاتح لأبواب الرحمة والرزق", explanation: "The One who opens what is closed — mercy, provision, and understanding." },
  { arabic: "الْعَلِيمُ", transliteration: "Al-Alim", meaning: "The All-Knowing", meaningAr: "العليم بكل شيء", explanation: "The One who knows all things, the seen and the unseen." },
  { arabic: "الْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Withholder", meaningAr: "القابض للأرزاق والأرواح بحكمته", explanation: "The One who withholds provision and takes souls by His wisdom." },
  { arabic: "الْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Extender", meaningAr: "الباسط للرزق والرحمة", explanation: "The One who extends provision and mercy to whom He wills." },
  { arabic: "الْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Abaser", meaningAr: "الذي يخفض المتكبرين", explanation: "The One who lowers the arrogant and the wrongdoers." },
  { arabic: "الرَّافِعُ", transliteration: "Ar-Rafi'", meaning: "The Exalter", meaningAr: "الذي يرفع المؤمنين والأولياء", explanation: "The One who raises the believers and the righteous in honour." },
  { arabic: "الْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Honourer", meaningAr: "الذي يهب العزّة لمن يشاء", explanation: "The One who grants honour and might to whom He wills." },
  { arabic: "الْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Humbler", meaningAr: "الذي يذلّ من يشاء بعدله", explanation: "The One who brings low whom He wills, in perfect justice." },
  { arabic: "السَّمِيعُ", transliteration: "As-Sami'", meaning: "The All-Hearing", meaningAr: "السميع لكل صوت", explanation: "The One who hears every sound, however faint, and answers." },
  { arabic: "الْبَصِيرُ", transliteration: "Al-Basir", meaning: "The All-Seeing", meaningAr: "البصير بكل شيء", explanation: "The One who sees all things, however hidden." },
  { arabic: "الْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge", meaningAr: "الحاكم بين خلقه بالعدل", explanation: "The One who judges between creation with perfect justice." },
  { arabic: "الْعَدْلُ", transliteration: "Al-Adl", meaning: "The Utterly Just", meaningAr: "العادل في كل أحكامه", explanation: "The One who is perfectly just in all that He decrees." },
  { arabic: "اللَّطِيفُ", transliteration: "Al-Latif", meaning: "The Most Subtle and Kind", meaningAr: "اللطيف بعباده العليم بدقائق الأمور", explanation: "The One gentle with His servants, aware of the subtlest details." },
  { arabic: "الْخَبِيرُ", transliteration: "Al-Khabir", meaning: "The All-Aware", meaningAr: "العالم ببواطن الأمور", explanation: "The One fully aware of the inner reality of all things." },
  { arabic: "الْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Most Forbearing", meaningAr: "الذي لا يعجل بالعقوبة", explanation: "The One who does not hasten to punish despite disobedience." },
  { arabic: "الْعَظِيمُ", transliteration: "Al-Azim", meaning: "The Magnificent", meaningAr: "العظيم في ذاته وصفاته", explanation: "The One infinite in greatness and majesty." },
  { arabic: "الْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The Great Forgiver", meaningAr: "الغفور الساتر للذنوب", explanation: "The One who forgives abundantly and conceals faults." },
  { arabic: "الشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Most Appreciative", meaningAr: "الذي يجازي على القليل بالكثير", explanation: "The One who rewards even small good deeds many times over." },
  { arabic: "الْعَلِيُّ", transliteration: "Al-Ali", meaning: "The Most High", meaningAr: "العلي فوق كل شيء", explanation: "The One exalted high above all creation." },
  { arabic: "الْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Most Great", meaningAr: "الكبير الذي كل شيء دونه", explanation: "The One greater than all, beyond comprehension." },
  { arabic: "الْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "The Preserver", meaningAr: "الحافظ لخلقه", explanation: "The One who protects and preserves all that exists." },
  { arabic: "الْمُقِيتُ", transliteration: "Al-Muqit", meaning: "The Sustainer", meaningAr: "المقيت الذي يوصل الأقوات", explanation: "The One who nourishes and maintains every creature." },
  { arabic: "الْحَسِيبُ", transliteration: "Al-Hasib", meaning: "The Reckoner", meaningAr: "الكافي المحاسب لعباده", explanation: "The One who suffices His servants and calls them to account." },
  { arabic: "الْجَلِيلُ", transliteration: "Al-Jalil", meaning: "The Majestic", meaningAr: "الموصوف بالجلال والعظمة", explanation: "The One possessing true majesty and grandeur." },
  { arabic: "الْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Most Generous", meaningAr: "الكريم كثير الخير والعطاء", explanation: "The One abundant in generosity and nobility." },
  { arabic: "الرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "The Ever-Watchful", meaningAr: "المراقب لكل شيء", explanation: "The One who watches over and observes all things." },
  { arabic: "الْمُجِيبُ", transliteration: "Al-Mujib", meaning: "The Responsive", meaningAr: "المجيب لدعاء عباده", explanation: "The One who answers the supplication of those who call upon Him." },
  { arabic: "الْوَاسِعُ", transliteration: "Al-Wasi'", meaning: "The All-Encompassing", meaningAr: "الواسع العلم والرحمة والفضل", explanation: "The One whose knowledge, mercy and bounty embrace everything." },
  { arabic: "الْحَكِيمُ", transliteration: "Al-Hakim", meaning: "The All-Wise", meaningAr: "الحكيم في خلقه وأمره", explanation: "The One perfectly wise in all creation and command." },
  { arabic: "الْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Most Loving", meaningAr: "المحبّ لأوليائه", explanation: "The One who loves the believers and is beloved to them." },
  { arabic: "الْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Glorious", meaningAr: "الماجد ذو الشرف والكرم", explanation: "The One sublime in glory, honour and generosity." },
  { arabic: "الْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrector", meaningAr: "الباعث للخلق يوم القيامة", explanation: "The One who raises the dead to life on the Day of Judgement." },
  { arabic: "الشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "The Witness", meaningAr: "الشاهد على كل شيء", explanation: "The One who witnesses and is present over all things." },
  { arabic: "الْحَقُّ", transliteration: "Al-Haqq", meaning: "The Absolute Truth", meaningAr: "الحق الثابت وجوده", explanation: "The One whose existence and reality are the ultimate truth." },
  { arabic: "الْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee", meaningAr: "الوكيل الكافي القائم بالأمور", explanation: "The One entrusted with all affairs, who disposes them perfectly." },
  { arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The All-Strong", meaningAr: "القوي الكامل القدرة", explanation: "The One of complete and perfect strength." },
  { arabic: "الْمَتِينُ", transliteration: "Al-Matin", meaning: "The Firm", meaningAr: "الشديد القوة الذي لا يلحقه تعب", explanation: "The One of steadfast, unyielding might whom no fatigue touches." },
  { arabic: "الْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Protecting Friend", meaningAr: "الولي الناصر لعباده المؤمنين", explanation: "The supporter and guardian of the believers." },
  { arabic: "الْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praiseworthy", meaningAr: "المحمود على كل حال", explanation: "The One deserving of all praise in every state." },
  { arabic: "الْمُحْصِي", transliteration: "Al-Muhsi", meaning: "The All-Enumerating", meaningAr: "المحصي لكل شيء عدداً", explanation: "The One who counts and knows the exact number of all things." },
  { arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi'", meaning: "The Initiator", meaningAr: "المبدئ للخلق ابتداءً", explanation: "The One who originates creation without any prior example." },
  { arabic: "الْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "The Restorer", meaningAr: "المعيد للخلق بعد فنائهم", explanation: "The One who brings creation back to life after death." },
  { arabic: "الْمُحْيِي", transliteration: "Al-Muhyi", meaning: "The Giver of Life", meaningAr: "المحيي واهب الحياة", explanation: "The One who grants life to all living things." },
  { arabic: "الْمُمِيتُ", transliteration: "Al-Mumit", meaning: "The Bringer of Death", meaningAr: "المميت الذي يقدّر الموت", explanation: "The One who ordains death for every soul in its time." },
  { arabic: "الْحَيُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living", meaningAr: "الحي الذي لا يموت", explanation: "The One living eternally, without beginning or end." },
  { arabic: "الْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Subsisting Sustainer", meaningAr: "القائم بنفسه المقيم لغيره", explanation: "The One self-existing, upon whom all else depends." },
  { arabic: "الْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Perceiver", meaningAr: "الذي لا يعوزه شيء", explanation: "The One who lacks nothing and finds whatever He wills." },
  { arabic: "الْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Illustrious", meaningAr: "الماجد واسع الكرم والشرف", explanation: "The One abundant in glory, honour and majesty." },
  { arabic: "الْوَاحِدُ", transliteration: "Al-Wahid", meaning: "The One", meaningAr: "الواحد الذي لا شريك له", explanation: "The One singular, without partner or equal." },
  { arabic: "الْأَحَدُ", transliteration: "Al-Ahad", meaning: "The Unique", meaningAr: "الأحد الفرد الذي لا نظير له", explanation: "The One absolutely indivisible and unique." },
  { arabic: "الصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal Refuge", meaningAr: "الصمد الذي تُقصد إليه الحوائج", explanation: "The self-sufficient One whom all creation seeks and depends upon." },
  { arabic: "الْقَادِرُ", transliteration: "Al-Qadir", meaning: "The All-Capable", meaningAr: "القادر على كل شيء", explanation: "The One able to do all that He wills." },
  { arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Omnipotent", meaningAr: "المقتدر البالغ القدرة", explanation: "The One of perfect, prevailing power over everything." },
  { arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter", meaningAr: "الذي يقدّم ما يشاء", explanation: "The One who advances whom and what He wills." },
  { arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer", meaningAr: "الذي يؤخّر ما يشاء", explanation: "The One who delays whom and what He wills by His wisdom." },
  { arabic: "الْأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First", meaningAr: "الأول الذي ليس قبله شيء", explanation: "The One before whom there is nothing." },
  { arabic: "الْآخِرُ", transliteration: "Al-Akhir", meaning: "The Last", meaningAr: "الآخر الذي ليس بعده شيء", explanation: "The One after whom there is nothing." },
  { arabic: "الظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest", meaningAr: "الظاهر الذي فوق كل شيء", explanation: "The One evident by countless signs, above all things." },
  { arabic: "الْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden", meaningAr: "الباطن العالم بالخفايا", explanation: "The One nearer than all, yet hidden from perception." },
  { arabic: "الْوَالِي", transliteration: "Al-Wali", meaning: "The Governor", meaningAr: "الوالي المتولي لأمور الخلق", explanation: "The One who owns and manages every affair of creation." },
  { arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Most Exalted", meaningAr: "المتعالي عن كل نقص", explanation: "The One exalted far above every deficiency." },
  { arabic: "الْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of All Goodness", meaningAr: "البَرّ اللطيف بعباده", explanation: "The One kind and gracious, the source of all goodness to His servants." },
  { arabic: "التَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Accepter of Repentance", meaningAr: "الذي يقبل توبة عباده", explanation: "The One who accepts repentance and inspires servants to return to Him." },
  { arabic: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger", meaningAr: "المنتقم من العصاة بعدله", explanation: "The One who justly punishes the persistent wrongdoers." },
  { arabic: "الْعَفُوُّ", transliteration: "Al-Afuww", meaning: "The Pardoner", meaningAr: "العفو الذي يمحو الذنوب", explanation: "The One who effaces sins and pardons completely." },
  { arabic: "الرَّءُوفُ", transliteration: "Ar-Ra'uf", meaning: "The Most Kind", meaningAr: "الرؤوف الشديد الرحمة", explanation: "The One full of compassion and gentleness toward His servants." },
  { arabic: "مَالِكُ الْمُلْكِ", transliteration: "Malik-ul-Mulk", meaning: "Master of the Kingdom", meaningAr: "مالك الملك المتصرف فيه", explanation: "The sole owner of all dominion, granting and withdrawing it as He wills." },
  { arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Dhul-Jalali wal-Ikram", meaning: "Possessor of Glory and Honour", meaningAr: "ذو العظمة والفضل والكرم", explanation: "The One possessing supreme majesty as well as bounty and honour." },
  { arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable", meaningAr: "المقسط العادل في حكمه", explanation: "The One who acts with perfect fairness and equity." },
  { arabic: "الْجَامِعُ", transliteration: "Al-Jami'", meaning: "The Gatherer", meaningAr: "الجامع للخلق ليوم القيامة", explanation: "The One who gathers all creation on the Day of Judgement." },
  { arabic: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", meaning: "The Self-Sufficient", meaningAr: "الغني عن كل ما سواه", explanation: "The One in no need of anything, while all things need Him." },
  { arabic: "الْمُغْنِي", transliteration: "Al-Mughni", meaning: "The Enricher", meaningAr: "الذي يُغني من يشاء", explanation: "The One who enriches His servants as He wills." },
  { arabic: "الْمَانِعُ", transliteration: "Al-Mani'", meaning: "The Preventer", meaningAr: "المانع الحامي بحكمته", explanation: "The One who withholds and protects by His wisdom." },
  { arabic: "الضَّارُّ", transliteration: "Ad-Darr", meaning: "The Distresser", meaningAr: "الذي يقدّر الضرّ بحكمته", explanation: "The One by whose decree harm may reach whom He wills." },
  { arabic: "النَّافِعُ", transliteration: "An-Nafi'", meaning: "The Benefactor", meaningAr: "النافع الذي بيده النفع", explanation: "The One in whose hand lies all benefit, granted to whom He wills." },
  { arabic: "النُّورُ", transliteration: "An-Nur", meaning: "The Light", meaningAr: "النور هادي السماوات والأرض", explanation: "The Light of the heavens and the earth, the guide out of darkness." },
  { arabic: "الْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide", meaningAr: "الهادي إلى الحق", explanation: "The One who guides His servants to the truth." },
  { arabic: "الْبَدِيعُ", transliteration: "Al-Badi'", meaning: "The Incomparable Originator", meaningAr: "المبدع الخالق على غير مثال", explanation: "The One who creates in wondrous ways, without any precedent." },
  { arabic: "الْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting", meaningAr: "الباقي الذي لا يفنى", explanation: "The One who remains forever after all else perishes." },
  { arabic: "الْوَارِثُ", transliteration: "Al-Warith", meaning: "The Inheritor", meaningAr: "الوارث الباقي بعد فناء الخلق", explanation: "The One to whom everything returns after creation passes away." },
  { arabic: "الرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "The Guide to the Right Path", meaningAr: "الرشيد الذي أفعاله على سداد", explanation: "The One whose management of all affairs is perfect guidance." },
  { arabic: "الصَّبُورُ", transliteration: "As-Sabur", meaning: "The Most Patient", meaningAr: "الصبور الذي لا يعجل بالعقاب", explanation: "The One who does not hasten punishment upon the disobedient." },
];
